version: "3"

services:
    fixGeoCodes: # replace me with other script's name
        build:
            context: .
            # remember to delete your docker image if you need to build it again
            # https://docs.docker.com/compose/compose-file/build/#args
            # https://docs.docker.com/compose/compose-file/build/#secrets
            dockerfile: fixGeoCodes.dockerfile
            # remember the docker file to point to your script
            # TODO: if the script saves files, there must be a way to get them from the container
        network_mode: host
        env_file:
            - path: ./fixGeoCodes.env
              required: true # default


        # deploy:
        #     resources:
        #         limits:
        #             # you can limit how much memory or CPU you want a script to have here
        #             # cpus: "1.05" # got up to 50ish %
        # memory: "300MB" # got up to 100ish MB
