version: "3"

services:
    script:
        build:
            context: .
            # replace this with your docker file
            # TODO: have to figure a way to pass args to the script and define them here
            # https://docs.docker.com/compose/compose-file/build/#args
            # https://docs.docker.com/compose/compose-file/build/#secrets
            dockerfile: fixGeoCodes.dockerfile
        network_mode: host
        # deploy:
        #     resources:
        #         limits:
        #             # you can limit how much memory or CPU you want a script to have here
        #             # cpus: "1.05" # got up to 50ish %
        # memory: "300MB" # got up to 100ish MB
